### PR TITLE
Fix Slic3r repo path

### PR DESCRIPTION
**Pull request by bneiluj**
Fix Slic3r repo path so then people can copy link

### CODE REVIEW

**Comment by bubnikv** [comment]
I don't think your change is correct. The path is already enclosed in double quotes.

**Comment by bneiluj** [comment]
I'm afraid that the change is correct. 
If you try to access `"~/Library/Application Support/Slic3r/"` you will get `"No such file or directory"`. 
In mac you need to add `\` for accessing Application Support = `"~/Library/Application\ Support/Slic3r/
screen shot 2017-10-12 at 18 35 56
"`

**Comment by bubnikv** [comment]
You have to copy the path including the quotes. Then it will work.

**Comment by bneiluj** [comment]
Sorry but It will not work except if you use those ones: 

```
cd ~/'Library/Application Support/'
cd ~/Library/Application\ Support/
cd "$HOME/Library/Application Support/"
```

In the file it's written: `"~/Library/Application Support/Slic3r/"` which cannot work regardless you include the quotes.

**Comment by bneiluj** [comment]
screen shot 2017-10-12 at 21 00 24

(as you seem to be very persistent 😅)

**Comment by bubnikv** [comment]
I see, I should dust off my command line skills. I did not expect the tilde
~ not being interpreted when enclosed in the quotes.

> as you seem to be very persistent

I am quite busy and I don't know what are the skills of the person on the
other side of the wire. Sorry about that.

On Thu, Oct 12, 2017 at 10:01 PM, Julien Bouteloup <notifications@github.com

**Comment by bneiluj** [comment]
No worries. 
I know what you mean :) 
(btw I've been around programming for a (very) long time ;) )

**Comment by rtyr** [comment]
I believe this PR is no longer valid. Closing.

**Pull request closed without merging**
