### PR TITLE
Update anycubic mega

### PR DESCRIPTION
**Pull request by Igami**

### CODE REVIEW

**Comment by Igami** [comment]
I messsed up the rebase :sob:

**Comment by rtyr** [comment]
Maybe just attach the final ini file to the comments, I will push it manually anyway.

**Comment by Igami** [comment]
What is the best practice to avoid messing up with filenames in the future?
Copy the ini file with a prefix like "0.0.10-igami" so there is no conflict possible when you forget to fetch updates?

I've started my work based on 0.0.7 ini and then fetched the updates an need to change it to 0.0.10

**Comment by rtyr** [comment]
Best practice is to not forget to fetch the updates :-). It doesn't matter much, because I usually push the updates manually, based on the current situation with that specific bundle. 

For example, there is another PR to the same Anycubic bundle https://github.com/prusa3d/PrusaSlicer/pull/6452 (it cannot be released on-line now).

**Comment by Igami** [comment]
I'm done now ... again :)

**Comment by rtyr** [comment]
Sorry, I will remove your long deretract/retract from your start/end gcode again. I understand you are used to it, but it assumes that print job is always succesfull, which is often not the case.

**Comment by Igami** [comment]
How about a longer intro line?
If the filament is already in the nozzle, it starts immediately, otherwise only after a certain distance.

**Comment by rtyr** [comment]
I don't know, I think most of the users just don't expect the filament to be unloaded after print, it is unusual behavior.

**Comment by Igami** [comment]
Unusual, but very practical for bowden extruders. The MMU also unloads the filament independently.

I make another commit and then you can decide whether it is accepted or not. Give me  half an hour.

**Comment by rtyr** [comment]
`G1 X66.0 E38.0 F1000 ; deretract filament` Have you tried it with loaded filament? It will likely skip/slip heavily.

**Comment by rtyr** [comment]
As for the MMU, it loads the filament from the bondtech gears to the nozzle. If you stop the print on the MMU, FW will automatically unload the filament.

**Comment by Igami** [comment]
Sorry, I havn't tried it but your'e absolutly correct, that the load is to much for the short movement. I've changed it to a travel all over the X-Axis, but could test it first this evening

**Comment by Igami** [comment]
this is how the inital load looks like, when the filament wasn't retractec

photo_2021-05-05_14-03-10

**Comment by rtyr** [comment]
Better, but it is printing again over already printed path (`G1 X5.0 E19 F1000`).

What about something like this?

; initial load
G1 X205 E38 F1000 //**can Anycubic extruder handle this? (it can be slower)**
G92 E0.0
; intro line **// printed from the right side**
G1 Y2 Z0.2 F1000
G1 X145 E9 F1000
G1 X105 E12.5 F1000

**Comment by Igami** [comment]
I like that you are so attentive :)

I forgot to add a y movement after the first line.
It should be and was tested like this for the picture:
```ini
; initial load
G1 X205.0 E19 F1000
G1 Y 1.6
G1 X5.0 E19 F1000
G92 E0.0
```

**Comment by rtyr** [comment]
> I like that you are so attentive :)

:)

aaa

**Comment by rtyr** [comment]
Merged to master. Closing.

**Comment by Igami** [comment]
When will the update be available?

**Comment by rtyr** [comment]
It's live now.

**Comment by slghb** [comment]
Unfortunately some of these changes don't work well on our printer. With the [latest profile](https://github.com/prusa3d/PrusaSlicer/blob/f8a4c3c7ceb04a6d5d0759b7285b6e6bbc039d65/resources/profiles/Anycubic.ini) we see a lot of stringing. I checked with an older version of the profile and everything was working fine again.

I've seen a lot of parameters have been changed in [this commit](https://github.com/prusa3d/PrusaSlicer/commit/325ee3691c4acae37e54d8723eb5a080a3664bc8#diff-8fca6c35126606f7a53163d98555328f7926a27b64f15d3028127990ad3016d1) and I don't really understand where all the new values come from. I tested with reverting "retract_length" back to 6 and it improved print quality a lot. However the quality was still a bit worse than with the old profile.

Can you tell me where you got the new parameter settings from?

**Comment by rtyr** [comment]
@Igami Default retraction distance for Anycubic Mega is around 6mm, so current value (3.2mm) indeed looks rather insufficient.

Looking at the settings, it seems your recent changes were mainly inspired by our Prusa MINI settings. Prusa MINI uses completely different hotend, extruder, very short PTFE tube, LA, etc...

**Comment by rtyr** [comment]
It is this commit https://github.com/prusa3d/PrusaSlicer-settings/pull/131/commits/ada391d22793806d8dc90c51295b794513703a76.

**Comment by slghb** [comment]
Thanks for your response.

Today I tried with changing the following settings back to what they were before and I had no stringing anymore. I only tested with PLA for now.

retract_length: 6
retract_lift: 0.075
retract_speed: 40
deretract_speed: 50

However compared to a print with the old profile, the top layer (and it looks like also the layers below) still seems to have some issues as there are small gaps between the perimeters and the solid fill.

In general I would compare the Anycubic Mega more to the Prusa MK2, except for the bowden extruder, which is of course different.

@Igami is there any special reason why you changed the fill_pattern only on the 0.3mm layer height to from gyroid to grid?

Also just looking at the settings I'm wondering if max_print_speed=200 is not too fast. The Prusa MK2 has 100 by default here and I would be surprised if the Anycubic is better than the MK2.

other settings I found that are greater than the MK2 default settings (values given below):
bridge_speed = 25 (currently 30)
first_layer_acceleration = 800 (currently  1000)
solid_infill_speed = 50 (currently  80)
top_solid_min_thickness = 0.7 (currently  0.6)

**Comment by Igami** [comment]
Sorry for the late replay and the issues.
I will try to explain how I got to these Settings:

I was unsatisfied with the print quality compared to the parts from the original Prusa Printer, so I started printing with the print settings from the prusa profile wich looked much better except for Stringing.
So I was looking for some retraction settings, the "old one" took quite amount of time so I tried the one from the Prusa Bowden Extruder which worked for the Formfutura PLA also. These Tests I could only do on the Mega S which has a geared extruder. Maybe that's the reason for stringing on the Mega.
The infill pattern for 0.3mm layer height is just copied from the prusa profile.

You're welcome to add better settings to the profiles :slightly_smiling_face: 

I will do some stringing tests in the future before changing print settings.
At this time I just printed cubes and some benchys.

**Comment by slghb** [comment]
Hi @Igami, thanks for your response.

I also have access to a Mega S here, but until now I did all my tests with the Mega. When I find some time I could also test the Mega S if I see any difference. I'm currently using the Filament from DasFilament, with the "old" settings we didn't have any stringing issues there.
I will do some more tests when time permits and then create a pull request with my updates. I can tag you then so you can then also test the settings on your printer.

**Comment by slghb** [comment]
Hi @Igami, just a quick question, where did you get the "machine_max_feedrate_e = 30" for the Anycubic i3 Mega S from? I didn't see this value anywhere and the source code for the Mega S has the value 60 (same as i3 Mega):
https://github.com/ANYCUBIC-3D/MEGA_S/blob/master/Configuration.h#L508

**Comment by Igami** [comment]
https://github.com/davidramiro/Marlin-Ai3M#after-obtaining-the-hex-file

> **If you are using this on a Mega-S, those four additional commands are necessary:**
> - `M92 E384` - set correct steps for the new extruder
> - `M203 E30` - limit extruder feedrate

**Pull request closed without merging**
