### PR TITLE
Refactored Ultimaker 2 printer and added Ultimaker 2 DXUv2 mod and new Ultimaker S-line printers (S3/S5/S7)

### PR DESCRIPTION
**Pull request by ansonl**
Refactored existing Ultimaker 2 profile to remove repeated values and changed some values to the new updated Cura values.

Added the [Ultimaker 2 DXUv2 mod](https://github.com/ansonl/DXU).
Added all [Ultimaker S-line](https://ultimaker.com/3d-printers/s-series/) printers.

The Ultimaker Griffin Gcode header required by the Ultimaker S-line printers is created in the start G-code. 
Users of Ultimaker S-line printers may need to manually remove the PrusaSlicer added header from the G-code before sending it to the printer because the Ultimaker S-line printers check for the `; generated by PrusaSlicer` on the first line and will say that the G-code file has an "error" if found. 

I tested this profile to work with a dual color print on an Ultimaker S7. The S3, S5, and S7 are the same besides for the difference in build volume.

image

### CODE REVIEW

**Comment by rtyr** [comment]
- Can I ask for the reason, why are all three S printers grouped to one printer called "S-line"?
- There are no print profiles available for Ultimaker S3/S5 and S7.
- `max_layer_height` and `min_layer_height` cannot be specified within print profiles (it belongs to printer profile).

**Comment by ansonl** [comment]
@rtyr 
1. I grouped all the S printers into one initial category because their mechanical operation and software is the same. The only difference between the models is: S3 has smaller bed size and S7 has a pei buildplate. 
2. The print profile settings (separate from the printer specific settings like bed volume) are identical between the printers due to **1**. I added the printers like `[printer:Ultimaker S3]` in the ini. Does there need to be a duplicate of the same print profile between each of them? 

3 & 4. I updated the files like you said.

**Comment by rtyr** [comment]
> I grouped all the S printers into one initial category because their mechanical operation and software is the same. The only difference between the models is: S3 has smaller bed size and S7 has a pei buildplate.

I see, but I imagine if I owned one of those printers, for example S3, I would prefer to see only the S3 (and possibly other printers I actually have) in the printer profile selection, not S3, S5, S7. It is basically only about adding two extra thumbnails and simple change in the ini file, but I guess it can stay as "S-line" group.

> The print profile settings (separate from the printer specific settings like bed volume) are identical between the printers due to 1. I added the printers like [printer:Ultimaker S3] in the ini. Does there need to be a duplicate of the same print profile between each of them?

That is not what I meant- There are literally no print profiles available for S3/S5/S7 (it is not possible to slice anything). Existing print profiles are set to be compatible only with Ultimaker 2 (`printer_model=="ULTIMAKER2" and nozzle_diameter[0]==0.4`)

**Comment by ansonl** [comment]
@rtyr Got it, I updated the print profiles to include the Sline printers. 

I also added better thumbnails so the printers are "facing" the same angle in the pictures.

**Pull request merged**
