### PR TITLE
Add AnkerMake M5 3D printer

### PR DESCRIPTION
**Pull request by ankermake**
Dear Prusa Team,

I am writing on behalf of AnkerMake, a company dedicated to providing high-quality 3D printing solutions. We have recently developed a new printer profile for the PrusaSlicer software and would like to request its inclusion in the official PrusaSlicer Profile Github repository.

We have thoroughly tested and validated our profile and believe that it would be a valuable addition to the existing collection. Our profile has been designed to optimize the performance of our printers AnkerMake M5 and to provide users with an enhanced printing experience. We believe that this profile will be beneficial for all PrusaSlicer users, especially those who use our printers.

We would be honored if our profile could be made available in the upcoming versions of PrusaSlicer, including versions 2.5, 2.6, and any subsequent updates. Our team is committed to maintaining and updating the profile to ensure its continued compatibility with the latest software versions.

Thank you for considering our request. We are excited about the opportunity to collaborate with your team and contribute to the 3D printing community.

Please let us know if you require any further information or testing of our profile.

Best regards,
AnkerMake Dev Team

### CODE REVIEW

**Comment by rtyr** [comment]
We noticed that your repositories were not updated at all since first publishing. Please update those repositories first to comply with the GPL licence.

https://github.com/ankermake/AnkerMake-Slicer
https://github.com/ankermake/AnkerMake-Marlin

**Comment by just-trey** [comment]
> We noticed that your repositories were not updated at all since first publishing. Please update those repositories first to comply with the GPL licence.
> 
> https://github.com/ankermake/AnkerMake-Slicer https://github.com/ankermake/AnkerMake-Marlin

@rtyr I will work with @ankermake to fix this. but can you help me understand what this repo is for vs. submitting profiles to this location? https://github.com/prusa3d/PrusaSlicer/tree/master/resources/profiles

**Comment by carycheung** [comment]
> We noticed that your repositories were not updated at all since first publishing. Please update those repositories first to comply with the GPL licence.
> 
> https://github.com/ankermake/AnkerMake-Slicer https://github.com/ankermake/AnkerMake-Marlin

We will update it ASAP. Thanks for notifying us.

**Comment by rtyr** [comment]
@just-trey this repo is mainly about on-line configuration updates, which are automatically downloaded by PrusaSlicer application. It is ok to place updates just to this repository.

**Comment by rtyr** [comment]
Merged manually. Since there were already community made AnkerMake profiles, I had to change version and rename some resource files (thumbnail, texture). I also resized the thumbnail to standard resolution used in the wizard.

Profiles are available for PrusaSlicer 2.6.0-alpha4 and newer (2.6.0-alpha can also automatically update the thumbnail and other resources).

https://github.com/prusa3d/PrusaSlicer-settings/tree/master/live/Anker

**Pull request closed without merging**
