### PR TITLE
Fix oozing problem while mesh bed leveling before starting a print.

### PR DESCRIPTION
**Pull request by jeffreydevreede**
If have added this starting gcode to my slic3r settings so that while my prusa i3 mk2s does mesh bed leveling at the start the extruder doesn't ooze plastic all over the heatbed.

A readable version of the gcode:

```
M115 U3.0.12 ; tell printer latest fw version
M83  ; extruder relative mode
M104 S160 ; set extruder to a temporary high enough temp
M140 S[first_layer_bed_temperature] ; set bed temp
M190 S[first_layer_bed_temperature] ; wait for bed temp
M109 S160 ; wait for extruder temporary high enough temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
M104 S[first_layer_temperature] ; set extruder actual required temp
M109 S[first_layer_temperature] ; wait for extruder actual required temp
G1 X60.0 E9.0  F1000.0 ; intro line
G1 X100.0 E12.5  F1000.0 ; intro line
```

### CODE REVIEW

**Comment by probonopd** [comment]
I second this. Default mesh bed leveling is leaving ooze all over the place, especially with a larger nozzle. With this it is much better! Is there any downside to this, besides the longer time it takes?

**Comment by probonopd** [comment]
This makes a __ton__ of difference for me. No more oozing crap around the printer.

**Comment by bubnikv** [comment]
I have asked @jindrichbenes to look into this, he is the guy responsible for our presets.

**Comment by bubnikv** [comment]
I have asked @jindrichbenes to evaluate this idea.
In the current Slic3r PE, one may use the conditional G-code to pre-heat the nozzle to a bit lower temperature:

M104 S{first_layer_temperature-10}
will preheat to -10oC lower temp.

**Comment by probonopd** [comment]
Thanks @bubnikv. What really matters is the default, as 99% of users will probably leave it as that. All I can say is that while the area around my printer was a mess before and I had to baby-sit each start of a print with PLA and a .6 mm nozzle, this is entirely fixed using the GCODE above. 

I am sceptic that 10 degrees lower than normal is sufficient. The GCODE above uses 160 degrees as the "high enough temp" and I did not encounter any problems with that temperature.

**Comment by bubnikv** [comment]
What is the "just enough" temperature just enough for? From our point of view, it should be just enough to soften whatever plastic collected on the nozzle or leaked from it, so it does would not stay in the way of the bed leveling. If the bed leveling was done with a cool nozzle, any plastic on the nozzle could be pushing the bed away from the nozzle before the PINDA triggers. Heating the nozzle high enough should lead to squishing the excess plastic instead.

**Comment by ctgreybeard** [comment]
@bubnikv I agree. I usually preheat my nozzle and bed before starting the print. Once the extruder is hot I clean it with tweezers. The hotend should be hot enough to allow the tweezers to remove the excess filament but not so hot as to allow it to ooze. A bit above glass temperature maybe?

**Comment by 3d-gussner** [comment]
@bubnikv Just tried to use your proposal
`M104 S{first_layer_temperature-30}; set extruder preheat temp`
but get
Slic3r has encountered an error (v1.41.0-alpha3+win64):
```
!!!!! Failed to process the custom G-code template start_gcode
Parsing error at line 3: Referencing a vector variable when scalar is expected
M104 S{first_layer_temperature-30}; set extruder preheat temp
       ^
!!!!! End of an error report for the custom G-code template start_gcode
```

**Comment by bubnikv** [comment]
Sorry, I did not test it myself. All the filament settings have to be
addressed with an extruder index using the new {} syntax. It should say
M104 S{first_layer_temperature[initial_tool]-30}; set extruder preheat temp

**Comment by 3d-gussner** [comment]
@bubnikv Works like a charm now! Thanks.

On my MK2 i move the extruder 50mm up to prevent the PINDAv1 to heat up. During the mesh bed leveling the hotend get to the fist_layer_temperature and can start the print.

Got the PINDAv2 and hope getting it soon connected to my MK2.2.1 (PINDAv2+NoctuaFan(withRPM)+my filament runout sensor). Next i will add the PAT9125 sensor so i have a MK2.3 (PINDAv2+NoctuaFan(withRPM)+PAT9125 filament sensor).

Here my start gcode:
```
M115 U3.1.0 ; tell printer latest fw version
M83  ; extruder relative mode
M104 S{first_layer_temperature[initial_tool]-30}; set extruder preheat temp
M140 S[first_layer_bed_temperature] ; set bed temp
G28 W ; home all without mesh bed level
G1 Z50; raise extruder before preheat
M190 S[first_layer_bed_temperature] ; wait for bed temp
M109 S{first_layer_temperature[initial_tool]-30} ; wait for extruder preheat temp
M104 S[first_layer_temperature] ; set extruder temp
G80 ; mesh bed leveling
M109 S[first_layer_temperature] ; wait for extruder temp
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0  F1000.0 ; intro line
G1 X100.0 E12.5  F1000.0 ; intro line
G92 E0.0
```
and the generated gcode:
```
; generated by Slic3r Prusa Edition 1.41.0-alpha3+win64 on 2018-08-03 at 10:42:32

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M201 X9000 Y9000 Z500 E10000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z12 E120 ; sets maximum feedrates, mm/sec
M204 S2000 T1500 ; sets acceleration (S) and retract acceleration (T), mm/sec^2
M205 X10.00 Y10.00 Z0.20 E2.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M115 U3.1.0 ; tell printer latest fw version
M83  ; extruder relative mode
M104 S200; set extruder preheat temp
M140 S85 ; set bed temp
G28 W ; home all without mesh bed level
G1 Z50; raise extruder before preheat
M190 S85 ; wait for bed temp
M109 S200 ; wait for extruder preheat temp
M104 S230 ; set extruder temp
G80 ; mesh bed leveling
M109 S230 ; wait for extruder temp
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0  F1000.0 ; intro line
M73 Q0 S68
M73 P0 R65
G1 X100.0 E12.5  F1000.0 ; intro line
G92 E0.0
M900 K45; Filament gcode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2

```

May i ask you another question? I try to generate the filename but adding {fill_pattern} or {external_fill_pattern} get again errors.
This works:
`{input_filename_base}_{filament_type[0]}_{layer_height}mm_{perimeters}perm_{fill_density}percent_{printer_model}.gcode`
that doesn't
`{input_filename_base}_{filament_type[0]}_{layer_height}mm_{perimeters}perm_{fill_density}percent_{fill_pattern}_{printer_model}.gcode`


Thank you for that quick answer!

**Comment by Vedrillan** [comment]
When I started 3D printing with my MK3S I was annoyed by this, at the start of a print I had to wait for the hotend to heat up and then manually remove the small filament extruded by gravity. I do not remember where I discovered this trick but it made my printing experience much better as now I can start a print and not worry for that small filament to get stuck in the printed object.

Setting the nozzle to 160°C before the bed leveling seems to be a good value as it is cold enough to not have filament extruding by gravity and at the same time hot enough to soften whatever plastic collected on the nozzle and not get in the way of the bed leveling.

The only down side of this is when you have to do short consecutive prints. If the nozzle temp is >160°C, you will have to wait for it to cool down to 160°C on the next print. But that use case is pretty rare, I personally only have to do this when calibrating the first layer.

I personally wish this was in the default MK3S printer profiles and not something I had to discover.

**Comment by trashcandrummer** [comment]
Glad I found this ticket as I wanted to create a PR for this too.
I use something similar but without the temporary temperature settings:

`M83 ; extruder relative mode
G28 W ; home all without mesh bed level
M140 S[first_layer_bed_temperature] ; set bed temp
M190 S[first_layer_bed_temperature] ; wait for bed temp
M104 S[first_layer_temperature] ; set extruder temp
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
M109 S[first_layer_temperature] ; wait for extruder temp
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line`

In this case we heat up the bed, wait for bed temp, set extruder temp so the nozzle starts to heat up but then immediately start leveling and wait after the leveling for the nozzle to reach the final temperature. 

Even with 9x9 leveling the time it takes for the nozzle to heat up to the point that there is any oozing the printer already finished leveling. Have used this for more than 1 year now and it works without problems.

**Comment by marcosscriven** [comment]
Came to this repo looking for the same thing, sad to see it’s not been accepted in years. 

Could someone in the Prusa dev team state requirements for submissions please? I do appreciate there’s a high bar if this is to be a default for all your customers. But then we do need to know if it’s worth even trying to contribute here.

**Comment by rtyr** [comment]
https://github.com/prusa3d/PrusaSlicer-settings/issues/45#issuecomment-847007671

**Comment by rtyr** [comment]
We decided we will not change the behavior on existing models (MK2/MK3). Users who prefer alternative start g-code can create separate printer profile.

**Pull request closed without merging**
