### PR TITLE
Ultimaker profile: use classic intro line for nozzle priming

### PR DESCRIPTION
**Pull request by fleutot**
Still using a priming blob, because the amount of extrusion needed to start actually getting plastic out of the nozzle seemed unreliable. Probably because of possible retraction at the end of the previous print.

Then, a line like Prusaslicer does with (at least) the MK3S.

Here is a [video of how it looks like](https://youtu.be/PYDGeOXgxOc).
@foreachthing @rtyr 

I put that in a new file, I am not sure about versioning with file names. Here is the diff with the previous version, for convenience:

```
$ diff 1.0.0.ini 1.0.1.ini --color
12c12
< config_version = 1.0.0
---
> config_version = 1.0.1
399c399
< start_gcode = ; Printer_Settings_ID: [printer_settings_id]\n\n; # # # # # # START Header\nG21 	; metric values\nG90 		; absolute positioning\nM82 		; set extruder to absolute mode\nM107 		; start with the fan off\n\nG28 X0 Y0 Z0	; move X/Y/Z to endstops\nG1 X1 Y6 F15000; move X/Y to start position\nG1 Z35 F9000	; move Z to start position\n\n; Heat up bed and nozzle\nM190 S{first_layer_bed_temperature[0] - 5}	; wait for bed temperature - 5\nM140 S[first_layer_bed_temperature]	; continue bed heating\nM109 S[first_layer_temperature]	; wait for nozzle temperature\n\nG92 E0		; zero the extruded length\nG1 F150 E22	; purge nozzle with filament\nG92 E0		; zero the extruded length again\nG1 F75 E7	; additional priming\nG92 E0		; zero the extruded length again\n\n; # # # # # # END Header
---
> start_gcode = start_gcode = ; Printer_Settings_ID: [printer_settings_id]\n\n; # # # # # # START Header\nG21 		; metric values\nG90 		; absolute positioning\nM82 		; set extruder to absolute mode\nM107 		; start with the fan off\n\nM140 S[first_layer_bed_temperature]	; start bed heating\n\nG28 X0 Y0 Z0	; move X/Y/Z to endstops\nG1 X1 Y6 F15000	; move X/Y to start position\nG1 Z35 F9000	; move Z to start position\n\n; Wait for bed and nozzle temperatures\nM190 S{first_layer_bed_temperature[0] - 5}	; wait for bed temperature - 5\nM140 S[first_layer_bed_temperature]	; continue bed heating\nM109 S[first_layer_temperature]	; wait for nozzle temperature\n\n; Purge and prime\nM83 		; set extruder to relative mode\nG92 E0           ; reset extrusion distance\nG0 X0 Y1 F10000\nG1 F150 E20 Y10  ; compress the bowden tube\nG1 E-8 F1200\nG0 X30 Y1 F5000    \nG0 F1200 Z{first_layer_height/2} ; Cut the connection to priming blob\nG0 X100 F10000 ; disconnect with the prime blob\nG0 X50         ; Avoid the metal clip holding the Ultimaker glass plate\nG0 Z0.2 F720\nG1 E8 F1200\nG1 X80 E3 F1000  ; intro line 1\nG1 X110 E4 F1000 ; intro line 2\nG1 X140 F600        ; drag filament to decompress bowden tube\nG1 X100 F3200       ; wipe backwards a bit\nG1 X150 F3200       ; back to where there is no plastic: avoid dragging\nG92 E0           ; reset extruder reference\nM82 		; set extruder to absolute mode\n\n; # # # # # # END Header

```

### CODE REVIEW

**Comment by rtyr** [comment]
Thanks, @foreachthing are also ok with this solution?

**Comment by fleutot** [comment]
Yeah, I wondered about that. Because the prime line should not be dependent on the model, so even for the other one, it should probably be a fixed value.

If anything, much of this should be dependent on nozzle diameter, I guess.

**Comment by foreachthing** [comment]
> If anything, much of this should be dependent on nozzle diameter, I guess.

You're absolutely right!

**Comment by fleutot** [comment]
Oh I was going to ask about index.idx, but I saw you just fixed that, thanks @rtyr .

**Comment by foreachthing** [comment]
image
This has not been fixed... should I start an issue?

**Comment by rtyr** [comment]
I am afraid I don't understand. Can you send me link where this was discussed?

**Comment by rtyr** [comment]
@fleutot @foreachthing 
Unfortunately, the new start g-code causes issues in the preview. Can we remove Y10 from this line?


nn

nn1

**Comment by rtyr** [comment]
Personally I would just remove the whole blob/purging and possibly redundant retraction in the end-gcode. Also it is maybe a good idea to use additional skirt, because it will stabilize the pressure in the nozzle better than aggressive purge line.

**Comment by foreachthing** [comment]
> I am afraid I don't understand. Can you send me link where this was discussed?

Just below this https://github.com/prusa3d/PrusaSlicer-settings/pull/153#issue-1171393548
I started a review (not sure it was done correctly)

**Comment by rtyr** [comment]
> Just below this https://github.com/prusa3d/PrusaSlicer-settings/pull/153#issue-1171393548
> I started a review (not sure it was done correctly)

Hmm I don't see anything.

**Comment by foreachthing** [comment]
Odd.
image

**Comment by fleutot** [comment]
How weird is that? Is the gcode wrong, or is it a bug in the preview? If the latter, we can still change the start_gcode so that it doesn't show, but that bug should be reported to the preview code repo.

I tried to remove the blob, but many times I would then get no extrusion for the line. It seems hard to count on where the filament is in the tube. The end_gcode of this profile, for example, retracts a bit at the end. I'm not sure what other end_gcodes usually do, if there is some kind of standard way of retracting at the end, then we should make this profile do that.

You can absolutely remove the Y10, but keep the rest of the row to keep the purge blob. I'm afraid we'd lose the line otherwise.

As for additional skirt, I'm not sure what you mean. Skirt around the model is at the discretion of the user, it's a print setting rather than printer setting?

**Comment by rtyr** [comment]
> How weird is that? Is the gcode wrong, or is it a bug in the preview? If the latter, we can still change the start_gcode so that it doesn't show, but that bug should be reported to the preview code repo.

I am not sure if it should be considered a bug, we will discuss it internally. It is quite unusual situation, because you are basically printing line in Z35 (from the g-code point of view). I will just remove the Y10 for now.

> As for additional skirt, I'm not sure what you mean. Skirt around the model is at the discretion of the user, it's a print setting rather than printer setting?

Yes, I meant print setting (using skirt around the object as default setting). But it was just side note, no need to change it.

**Comment by rtyr** [comment]
@foreachthing

I don't see your review, but I fixed it.

@fleutot 

1.0.2 update is live. Removed Y10 + fixed double start_gcode.

**Comment by foreachthing** [comment]
> Personally I would just remove the whole blob/purging and possibly redundant retraction in the end-gcode. 

I added the final retraction because I had problems with (waaaay back in time) the original Cura end-gcode not retracting enough to switch the nozzle. So, I kept increasing the retraction amount until no filament was left in the nozzle.
Back then I took the default Cura start- and end-gcode and just changed the extrusion amounts.

Then we installed the Bontech extruder and this issue was gone - but not everybody has one... so, I'd leave at that until someone else finds a better value.
As of now, I know of only _one_ person who uses this Ultimaker profile (with issues/concerns) ;-)

**Comment by fleutot** [comment]
>  As of now, I know of only _one_ person who uses this Ultimaker profile (with issues/concerns) ;-)

Is it me? I just love that it's there, and I don't understand why there aren't more people using it. I'm just going to be mentioning it to people, thanks for doing this.

**Comment by fleutot** [comment]
@rtyr 
> Also it is maybe a good idea to use additional skirt
> I meant print setting (using skirt around the object as default setting). But it was just side note, no need to change it.

Oh, yes, I do want higher skirt by default, but that's because I'm using a textured sheet and not the original Ultimaker glass plate. I didn't want to make it in the same PR, since it's addressing different problems.

I think it would make sense to match the defaults of other printers. If people switch from Cura to PrusaSlicer for their Ultimaker, it's not to get a profile that mimics Cura. So skirt at 3 layers by default: yes please.

**Comment by fleutot** [comment]
>  It is quite unusual situation, because you are basically printing line in Z35 (from the g-code point of view). I will just remove the Y10 for now.

I see. But the line from X50 to X110 is not at Z35, and still it displays at fat negative Z. I totally understand that this would not be prioritized.

**Comment by rtyr** [comment]
> I see. But the line from X50 to X110 is not at Z35, and still it displays at fat negative Z. I totally understand that this would not be prioritized.

We are looking into it.

**Pull request merged**
