### PR TITLE
Artillery

### PR DESCRIPTION
**Pull request by SzabolcsHornyak**
Fixed findings

### CODE REVIEW

**Comment by SzabolcsHornyak** [comment]
Do I need to make a new pull request for the resources or you can add it manually?
[https://github.com/prusa3d/PrusaSlicer-settings/files/5958171/Artillery.zip](url)

**Comment by rtyr** [comment]
I will add it manually.

**Comment by SzabolcsHornyak** [comment]
Thank you very much @rtyr in the name of the community!

**Comment by rtyr** [comment]
I fortgot to mention one thing. I noticed, that brim is always enabled in all profiles. It seems weird to me, is it intended? It is usually used only when needed. Shoudln't be skirt used instead?

**Comment by SzabolcsHornyak** [comment]
Yes it's intended. I prefer brim beacuse the printed model never popup. 
But if this setting is not standard we can change to skirt.
What is your opinion?

**Comment by rtyr** [comment]
I will change it for now, I don't think it should be enabled by default (and I am not aware of any other printer profile with this enabled by default). I will do it myself, no need to update the pull request.

**Comment by rtyr** [comment]
Added manually to the master. It will be included in the next PrusaSlicer release. Thank you.
Closing.

**Pull request closed without merging**
